### PR TITLE
Support dynamic (mutable) context

### LINKED ISSUE #40: Give template::context::Context a mut receiver
I have an application where I'd like to track the variables visited while expanding a URITemplateStr; currently that requires a pair of `Arc<Mutex<_>>` to avoid the mutability constraint on `Context` - it'd be great if the `Context` trait's `visit()` received `&mut self`.

Since that would likely be a breaking change, could we add a `MutContext`/`visit_mut()` and a corresponding method on `UriTemplateStr` (i.e. `expand_mut()`)?

### PR DESCRIPTION
**Pull request by lo48576**
Closes #40.

### CODE REVIEW

**Comment by nyarly** [comment]
That looks marvelous. I look forward to using it!

**Comment by lo48576** [comment]
@nyarly Let me make sure, is this ok for you to be released? Or are you trying this now and not yet completed the evaluation?

**Comment by nyarly** [comment]
I would use this as soon as it was released. If you want to hold a release for me to try it out, I can probably do that today.

**Comment by lo48576** [comment]
Ok, then I'll release this now. Thank you.

**Comment by nyarly** [comment]
Following up: switched to DynamicContext, works great. A little wrinkle switching to expand_dynamic_*, but figured it out. Thanks again.

**Pull request merged**
